[package]
name = "surrealism_all"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["surrealism", "surrealism_tools","tests"]
